FROM python:3.8.13

# DONE
# Add all the necessary to run the script populate_db.py in this image
# 1. Copy the requirements.txt file to the image
# 2. Install the dependencies
# 3. Copy the content of the current directory to the image
# 4. Run the populate_db.py script

WORKDIR /app
COPY ./requirements.txt /app
RUN pip install --no-cache-dir -r requirements.txt && pip install --no-cache-dir "psycopg2-binary>=2.9.5"
COPY . /app
CMD ["python", "populate_db.py"]